# Coffee Selection
coffee:
  - id: "black_whole_signature"
    name: "Black Whole Signature"
    price: 3.50
    image: "/assets/images/black.png"
    description: "Deep, dark, and essential. Our signature high-performance roast."
  
  - id: "medium_orbit"
    name: "Medium Orbit"
    price: 3.50
    image: "/assets/images/medium.png"
    description: "Balanced acidity with notes of caramel and toasted nuts."

  - id: "sweet_event_horizon"
    name: "Sweet Event Horizon"
    price: 3.80
    image: "/assets/images/sweet.png"
    description: "A smoother, lighter profile for a gentle morning pull."

# Edibles
edibles:
  - id: "turkey_sandwich"
    name: "Artisan Turkey Sandwich"
    price: 5.50
    image: "/assets/images/sandwich.png" # Placeholder name
    description: "Freshly made daily by our local partner."
