# Coffee Selection - In-House Production
coffee:
  - id: "black_signature"
    name: "Black Whole Signature"
    price: 3.50
    image: "/assets/images/black.png"
    description: "Our darkest orbit. High-performance caffeine with a bold finish."

  - id: "medium_orbit"
    name: "Medium Orbit"
    price: 3.50
    image: "/assets/images/medium.png"
    description: "Balanced notes of caramel and roasted nuts for a steady morning."

  - id: "sweet_horizon"
    name: "Sweet Event Horizon"
    price: 3.80
    image: "/assets/images/sweet.png"
    description: "A smoother, lighter profile for a gentle transition into the day."

# Edibles - Third-Party Producer
edibles:
  - id: "artisan_turkey"
    name: "Artisan Turkey Sandwich"
    price: 5.50
    producer: "Third-Party Kitchen"
    description: "Freshly prepared daily by our local partners."
